# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: false
cache: packages
use_bioc: true
notifications:
  email: false
  slack:
    secure: dAvLVXc8zEwZNDG4pceg7UmUjDr0ait9ntKG5XUoTE1WatYYlxF6sVQ+DUbTa7y/5h8tkbdhDrZMxYFbaWt+GAnIAyhj5ounupC9U1shIBWcdPE063MSj9lppOKYwZVoYl8HSIrA1AhNzJVPZKn/afqBwUBcfD8XJgAVQgo6Tgj7d0rR5nqbpwFUpixHRVs2GMhy/VgQXrF4OyKCN3Auv2jiq0jGrZfGNyaeNpR6BqjTiC4qcrJ90C6z8W7Z5Frq51IMObj3Juzzk9BridmSIU0zuM80M/XQbUIhBtKLZpjRFQb166Yyec3CkarB6E/IS/yiBE16SgsJN5cbjzVHGsJGV8fkTmEIEayQNINTalNKdKU8K5EETxPwfaQ8nqVhd9IKbqvYEYLTHdROGxzHg+U19sSJlxTqmXDrrBJMbXk7+9Zk5BAxejGBxHnYUtKz0kuM51JLfVK9X8ube0DB6TnfdR/VzbznXiw/gE5qW/uMuDW8e5NLDX8B7UxVHbn3yJKJon1OE4kO2MHg8tFCmahhnEru+iHibQzXrNEymIoJlHOzdK5+xI80+WsH2qFl9SW0ZPE2I9GnQliSoe0qlOms5lU/2k7LDzja9jdCZYdvySXuW7p69toSQ48lok5FDSg31BsWZH4D5G9s5rqvjKkfkKGnvOjptDiw1t542wA=
